In [1]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import psycopg2

In [2]:
# Pandas and Matplotlib Universal Options
%matplotlib inline
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 500)

In [3]:
# Connection to Postgres Yelp Database - Table: restaurant_reviews_final
conn = psycopg2.connect(database="yelp", user="postgres",
                        password='password', host="localhost", port="5432")
query = '''
        SELECT *
        FROM restaurant_reviews_final
        LIMIT 10000
        ;
        '''
df = pd.read_sql(query, conn)
# print(df.info())

In [4]:
# Creating a copy of the data to play around with.
test = df.copy()
test

,review_id,user_id,business_id,review_stars,review_date,review_text,review_useful,review_funny,review_cool,restaurant_name,restaurant_address,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_name,user_review_count,user_yelping_since,user_useful,user_funny,user_cool,user_elite,user_friends,user_fans,user_average_stars_given,user_compliment_hot,user_compliment_more,user_compliment_profile,user_compliment_cute,user_compliment_list,user_compliment_note,user_compliment_plain,user_compliment_cool,user_compliment_funny,user_compliment_writer,user_compliment_photos,restaurant_checkins
0,X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,2,0,3,Olive & Ivy,"7135 E Camelback Rd, Ste 195",Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,Ayla,421,2010-03-31 04:45:14,2205,927,1903,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,97,4,8,10,4,81,422,218,218,53,33,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010..."
1,2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,0,0,1,Riverside Fish House,1351 Dallas Stanley Hwy,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,Andrew,6,2015-05-12 19:44:07,1,0,1,,None,0,4.83,0,0,0,0,0,0,1,0,0,0,0,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013..."
2,RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,0,0,0,Famous Ray's Pizza,350 E Bell Rd,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,Felipe,21,2010-06-14 04:52:50,27,8,2,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,0,0,0,0,0,0,0,0,0,0,0,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010..."
3,5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,2,0,0,Press Coffee Food & Wine,Terminal 4 Gate B9,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,Ryne,684,2008-05-14 19:13:56,1390,814,770,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,34,6,2,1,9,33,46,57,57,30,0,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012..."
4,pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,0,0,0,Tacos El Tapatio,2014 W Ann Rd,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,Z,10,2012-08-29 06:35:52,4,0,2,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,0,0,0,0,0,0,0,0,0,0,0,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,tz6B342mmMBU1rc31IOkTg,IfipLBYviWuoA3i_pgLK_w,3kdSl5mo9dWC4clrQjEDGg,5,2009-04-01 22:07:10,You definitely have to try their version of a ...,0,0,0,Egg & I,"4533 W Sahara Ave, Ste 5",Las Vegas,NV,89102,36.144085,-115.202487,4.5,4048,1,"American (Traditional), Breakfast & Brunch, Pi...",2,Linda,198,2009-04-01 21:18:46,76,21,21,,"h5NxZjnGMES7391jdLUeiA, KLa-WHDtN-wjyPF8p1e4Cw...",5,3.78,0,0,0,1,0,0,3,1,1,4,0,"2010-01-16 19:35:04, 2010-03-20 17:09:44, 2010..."
9996,Qv07008njcCRTN7s3c8Eew,f5gw3C3jHrytKt69RB9eDA,4JkGjRRc3XucG9U8XwthGg,4,2012-02-15 05:52:49,I've order this place a few times always as ta...,1,0,1,China Gourmet,"2585 S Nellis Blvd, Ste 7",Las Vegas,NV,89121,36.142718,-115.066198,4.0,118,1,"Restaurants, Chinese",1,Kollin,48,2010-11-17 13:28:45,70,5,22,2012,"8ae6_UW4ZA2jI5pueR_hcA, tipQmXdg181T4NvxrXPjFg...",1,4.13,1,3,0,0,0,3,5,2,2,4,0,"2011-07-03 23:23:35, 2011-07-10 00:50:39, 2011..."
9997,9i6pkg-AMvqxVvFYI0pAGA,GGChQLPxvmLFnJ92iBlZ5w,A4zLP5AyKEEHQr_dWEZKig,3,2018-06-17 02:05:50,Definitely stop by. \n\nI was there for happy ...,1,0,0,Cleo,2535 S Las Vegas Blvd,Las Vegas,NV,89109,36.142249,-115.156616,4.5,582,0,"Restaurants, Mediterranean, Tapas/Small Plates...",3,Jorge,255,2010-05-29 13:58:33,306,86,64,,None,4,3.45,0,1,0,0,0,0,3,0,0,2,1,"2014-08-20 02:54:58, 2014-08-25 02:37:34, 2014..."
9998,kWkgrFUI2Q0R-95fOH7YMg,oBr8Hn68ecfX1DwvmjCtjw,i9mqSffakkmhtR_iyBnhnQ,3,2018-11-01 18:45:07,Clean modern design with pretty decent food! ...,0,0,1,Garionban,"4545 Spring Mountain Rd, Ste 102",Las Vegas,NV,89103,36.125990,-115.202470,4.0,132,1,"Restaurants, Barbeque, Asian Fusion, Soup, Korean",2,Michael,113,2013-01-13 16:29:42,200,27,90,2018,"GGTF7hnQi6D5W77_qiKlqg, 8GQ1L1Gn2ye-Lyyqf_zbIg...",4,4.01,0,2,0,0,0,2,3,5,5,2,2,"2018-01-03 00:28:04, 2018-01-03 03:41:18, 2018..."
9999,S970_2R0ow-9GKm7OIWitg,Bim-SoK8wItqFC5NqnN_Sw,3kdSl5mo9dWC4clrQjEDGg,4,2018-09-24 01:37:14,Shot almost made it to 5 stars really did ! On...,5,3,9,Egg & I,"4533 W Sahara Ave, Ste 5",Las Vegas,NV,89102,36.144085,-115.202487,4.5,4048,1,"American (Traditional), Breakfast & Brunch, Pi...",2,Sandy,232,2012-02-20 13:37:01,1291,478,1170,"2017,2018","BxJIjg_7Dl51OJICsVj4zg, 8DnaEGjMRuw0Hbohm3iHtA...",58,3.86,25,1,1,1,0,17,25,29,29,3,38,"2010-01-16 19:35:04, 2010-03-20 17:09:44, 2010..."

### Delete Unnecessary Columns

In [5]:
test.head(5)

,review_id,user_id,business_id,review_stars,review_date,review_text,review_useful,review_funny,review_cool,restaurant_name,restaurant_address,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_name,user_review_count,user_yelping_since,user_useful,user_funny,user_cool,user_elite,user_friends,user_fans,user_average_stars_given,user_compliment_hot,user_compliment_more,user_compliment_profile,user_compliment_cute,user_compliment_list,user_compliment_note,user_compliment_plain,user_compliment_cool,user_compliment_funny,user_compliment_writer,user_compliment_photos,restaurant_checkins
0,X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,2,0,3,Olive & Ivy,"7135 E Camelback Rd, Ste 195",Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,Ayla,421,2010-03-31 04:45:14,2205,927,1903,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,97,4,8,10,4,81,422,218,218,53,33,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010..."
1,2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,0,0,1,Riverside Fish House,1351 Dallas Stanley Hwy,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,Andrew,6,2015-05-12 19:44:07,1,0,1,,None,0,4.83,0,0,0,0,0,0,1,0,0,0,0,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013..."
2,RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,0,0,0,Famous Ray's Pizza,350 E Bell Rd,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,Felipe,21,2010-06-14 04:52:50,27,8,2,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,0,0,0,0,0,0,0,0,0,0,0,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010..."
3,5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,2,0,0,Press Coffee Food & Wine,Terminal 4 Gate B9,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,Ryne,684,2008-05-14 19:13:56,1390,814,770,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,34,6,2,1,9,33,46,57,57,30,0,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012..."
4,pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,0,0,0,Tacos El Tapatio,2014 W Ann Rd,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,Z,10,2012-08-29 06:35:52,4,0,2,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,0,0,0,0,0,0,0,0,0,0,0,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015..."

In [6]:
# Set Index to review_id
test.set_index('review_id', inplace=True, verify_integrity=True)

In [7]:
columns_to_drop = ['restaurant_name', 'restaurant_address', 'user_name']
test.drop(labels=columns_to_drop, axis=1, inplace=True)
test.head(5)

,user_id,business_id,review_stars,review_date,review_text,review_useful,review_funny,review_cool,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_useful,user_funny,user_cool,user_elite,user_friends,user_fans,user_average_stars_given,user_compliment_hot,user_compliment_more,user_compliment_profile,user_compliment_cute,user_compliment_list,user_compliment_note,user_compliment_plain,user_compliment_cool,user_compliment_funny,user_compliment_writer,user_compliment_photos,restaurant_checkins
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,2,0,3,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,2205,927,1903,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,97,4,8,10,4,81,422,218,218,53,33,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010..."
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,0,0,1,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,1,0,1,,None,0,4.83,0,0,0,0,0,0,1,0,0,0,0,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013..."
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,0,0,0,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,27,8,2,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,0,0,0,0,0,0,0,0,0,0,0,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010..."
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,2,0,0,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,1390,814,770,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,34,6,2,1,9,33,46,57,57,30,0,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012..."
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,0,0,0,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,4,0,2,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,0,0,0,0,0,0,0,0,0,0,0,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015..."

### Combine Columns Where Individual Columns are not Useful

In [8]:
# Combining sub-targets
# Consider weighting them separately in the future.
test['review_total_positives'] = test[['review_useful', 'review_funny', 'review_cool']].sum(axis=1)
test.head(5)

,user_id,business_id,review_stars,review_date,review_text,review_useful,review_funny,review_cool,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_useful,user_funny,user_cool,user_elite,user_friends,user_fans,user_average_stars_given,user_compliment_hot,user_compliment_more,user_compliment_profile,user_compliment_cute,user_compliment_list,user_compliment_note,user_compliment_plain,user_compliment_cool,user_compliment_funny,user_compliment_writer,user_compliment_photos,restaurant_checkins,review_total_positives
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,2,0,3,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,2205,927,1903,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,97,4,8,10,4,81,422,218,218,53,33,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,0,0,1,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,1,0,1,,None,0,4.83,0,0,0,0,0,0,1,0,0,0,0,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,0,0,0,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,27,8,2,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,0,0,0,0,0,0,0,0,0,0,0,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,2,0,0,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,1390,814,770,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,34,6,2,1,9,33,46,57,57,30,0,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,0,0,0,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,4,0,2,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,0,0,0,0,0,0,0,0,0,0,0,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0

In [9]:
test.drop(labels=['review_useful', 'review_funny', 'review_cool'], axis=1, inplace=True)

In [10]:
test['user_total_positives'] = test[['user_useful', 'user_funny', 'user_cool']].sum(axis=1)
test.drop(labels=['user_useful', 'user_funny', 'user_cool'], axis=1, inplace=True)
test.head()

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,user_compliment_hot,user_compliment_more,user_compliment_profile,user_compliment_cute,user_compliment_list,user_compliment_note,user_compliment_plain,user_compliment_cool,user_compliment_funny,user_compliment_writer,user_compliment_photos,restaurant_checkins,review_total_positives,user_total_positives
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,97,4,8,10,4,81,422,218,218,53,33,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,0,0,0,0,0,0,1,0,0,0,0,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,0,0,0,0,0,0,0,0,0,0,0,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,34,6,2,1,9,33,46,57,57,30,0,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,0,0,0,0,0,0,0,0,0,0,0,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6

In [11]:
compliment_columns = ['user_compliment_hot', 'user_compliment_more', 
                      'user_compliment_profile', 'user_compliment_cute',
                      'user_compliment_list', 'user_compliment_note',
                      'user_compliment_plain', 'user_compliment_cool',
                      'user_compliment_funny', 'user_compliment_writer',
                      'user_compliment_photos']
test['user_total_compliments'] = test[compliment_columns].sum(axis=1)
test.drop(labels=compliment_columns, axis=1, inplace=True)
test.head()

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,restaurant_checkins,review_total_positives,user_total_positives,user_total_compliments
review_id,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035,1148
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2,1
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37,0
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974,275
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6,0

### Split List Columns Into Useful Columns

In [12]:
def count_friends(x):
    friend_count = 0 
    if x in ['None', None, '']:
        friend_count = 0
    else:
        y = x.split(',')
        friend_count = len(y)
    return friend_count


test['user_friends_count'] = test.user_friends.apply(count_friends)
test.head(10)

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,restaurant_checkins,review_total_positives,user_total_positives,user_total_compliments,user_friends_count
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035,1148,1596
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2,1,0
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37,0,729
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974,275,264
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6,0,1
U7nueKweTWeqhhVDrVoRMw,sksyFBCtJdEq_lUlHTxxng,ZOmf-3NN4Z59b2Fw6VAM7g,5,2015-02-23 16:19:07,"amazing breakfast, amazing red potatoes and sk...",Las Vegas,NV,89147,36.113917,-115.308625,4.5,797,0,"Burgers, American (Traditional), Restaurants, ...",2,4,2011-10-29 04:49:17,,"eyk9XgNeeWPOs_f_qg-Ubg, eH1OL2gu9dW0hvzBD-DA_Q...",1,4.00,"2014-10-28 17:30:11, 2014-10-29 20:57:57, 2014...",0,12,1,323
s6KNw-8_kefMMtWWY1n_gw,RFKtICzEKGkgyu6DST9QjA,Q-fXNh68OldNdotEVEJuhQ,5,2018-09-13 22:03:13,Neighborhood bar were the locals hangout. Mad...,Henderson,NV,89052,36.006452,-115.111569,4.0,432,1,"American (New), Nightlife, Bars, American (Tra...",2,119,2013-08-12 14:51:22,"2017,2018","gGuAM6Cw1VXJGLssm24ehA, BhawhWz3fD_apxlZv1sMeQ...",5,4.39,"2015-08-25 19:44:31, 2015-08-25 23:59:28, 2015...",0,129,22,69
P2El64nL_7PXJqEidv_C9A,MFGDwMQJijNc0mHv1s_BUQ,dc6sPg9kNliz_Cy2yX19tw,2,2014-02-18 04:13:04,Some friends and I were meeting up for sushi a...,Phoenix,AZ,85032,33.600378,-111.978651,3.0,267,1,"Japanese, Sushi Bars, Restaurants",2,180,2010-01-14 17:25:11,"2010,2011,2012,2013,2014","9YRFLVFVbHGAJ1weFx5zqw, PeLGa5vUR8_mcsn-fn42Jg...",22,3.94,"2010-04-08 02:23:53, 2010-05-31 20:18:16, 2010...",4,878,111,345
VyMj6vHkn_1OSYiwz88T3w,DEMQj549-Ez-CkSE4tHsKw,5N8R7ALESZ30EoAzVJtabw,4,2017-05-25 00:17:13,This small restaurant is located in Kensington...,Toronto,ON,M5T 2K2,43.654647,-79.400561,3.5,309,1,"Breakfast & Brunch, American (Traditional), Ch...",2,46,2011-05-19 14:26:15,,"4jErA6Yp8jDvJ355M45TZA, -XfmaPe3bc4LhvdjVbZvBQ...",1,4.00,"2015-03-04 17:09:37, 2015-03-04 23:59:28, 2015...",0,36,4,10
gtljdgwVcrucDtaJe1VIMA,4UgCYM-rbqzukAJyAU_95Q,wH4Q0y8C-lkq21yf4WWedw,4,2017-01-06 14:18:57,"Very clean and hip location, as most Nekter's ...",Scottsdale,AZ,85260,33.580474,-111.881062,4.0,98,1,"Acai Bowls, Restaurants, Gluten-Free, Ice Crea...",2,125,2012-04-30 01:23:49,2016,"kIP1SVkdxxY6Qq1zKt34mA, rpDeMW5uB6VtbwW67PJhlw...",9,4.37,"2015-01-18 16:13:04, 2015-01-20 21:21:56, 2015...",4,351,32,556

In [13]:
def count_elite(x):
    elite_count = 0 
    if x in ['None', None, '']:
        elite_count = 0
    else:
        y = x.split(',')
        elite_count = len(y)
    return elite_count

test['user_elite_count'] = test.user_elite.apply(count_elite)
test.head(10)

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,restaurant_checkins,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035,1148,1596,3
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2,1,0,0
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37,0,729,0
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974,275,264,10
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6,0,1,0
U7nueKweTWeqhhVDrVoRMw,sksyFBCtJdEq_lUlHTxxng,ZOmf-3NN4Z59b2Fw6VAM7g,5,2015-02-23 16:19:07,"amazing breakfast, amazing red potatoes and sk...",Las Vegas,NV,89147,36.113917,-115.308625,4.5,797,0,"Burgers, American (Traditional), Restaurants, ...",2,4,2011-10-29 04:49:17,,"eyk9XgNeeWPOs_f_qg-Ubg, eH1OL2gu9dW0hvzBD-DA_Q...",1,4.00,"2014-10-28 17:30:11, 2014-10-29 20:57:57, 2014...",0,12,1,323,0
s6KNw-8_kefMMtWWY1n_gw,RFKtICzEKGkgyu6DST9QjA,Q-fXNh68OldNdotEVEJuhQ,5,2018-09-13 22:03:13,Neighborhood bar were the locals hangout. Mad...,Henderson,NV,89052,36.006452,-115.111569,4.0,432,1,"American (New), Nightlife, Bars, American (Tra...",2,119,2013-08-12 14:51:22,"2017,2018","gGuAM6Cw1VXJGLssm24ehA, BhawhWz3fD_apxlZv1sMeQ...",5,4.39,"2015-08-25 19:44:31, 2015-08-25 23:59:28, 2015...",0,129,22,69,2
P2El64nL_7PXJqEidv_C9A,MFGDwMQJijNc0mHv1s_BUQ,dc6sPg9kNliz_Cy2yX19tw,2,2014-02-18 04:13:04,Some friends and I were meeting up for sushi a...,Phoenix,AZ,85032,33.600378,-111.978651,3.0,267,1,"Japanese, Sushi Bars, Restaurants",2,180,2010-01-14 17:25:11,"2010,2011,2012,2013,2014","9YRFLVFVbHGAJ1weFx5zqw, PeLGa5vUR8_mcsn-fn42Jg...",22,3.94,"2010-04-08 02:23:53, 2010-05-31 20:18:16, 2010...",4,878,111,345,5
VyMj6vHkn_1OSYiwz88T3w,DEMQj549-Ez-CkSE4tHsKw,5N8R7ALESZ30EoAzVJtabw,4,2017-05-25 00:17:13,This small restaurant is located in Kensington...,Toronto,ON,M5T 2K2,43.654647,-79.400561,3.5,309,1,"Breakfast & Brunch, American (Traditional), Ch...",2,46,2011-05-19 14:26:15,,"4jErA6Yp8jDvJ355M45TZA, -XfmaPe3bc4LhvdjVbZvBQ...",1,4.00,"2015-03-04 17:09:37, 2015-03-04 23:59:28, 2015...",0,36,4,10,0
gtljdgwVcrucDtaJe1VIMA,4UgCYM-rbqzukAJyAU_95Q,wH4Q0y8C-lkq21yf4WWedw,4,2017-01-06 14:18:57,"Very clean and hip location, as most Nekter's ...",Scottsdale,AZ,85260,33.580474,-111.881062,4.0,98,1,"Acai Bowls, Restaurants, Gluten-Free, Ice Crea...",2,125,2012-04-30 01:23:49,2016,"kIP1SVkdxxY6Qq1zKt34mA, rpDeMW5uB6VtbwW67PJhlw...",9,4.37,"2015-01-18 16:13:04, 2015-01-20 21:21:56, 2015...",4,351,32,556,1

In [14]:
def most_recent_elite(x):
    most_recent = 0 
    if x in ['None', None, '']:
        most_recent = 0
    else:    
        y = x.split(',')
        most_recent = max(y)
    return most_recent

test['user_elite_most_recent'] = test.user_elite.apply(most_recent_elite)
test.head(10)

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,restaurant_checkins,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count,user_elite_most_recent
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035,1148,1596,3,2016
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2,1,0,0,0
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37,0,729,0,0
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974,275,264,10,2018
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6,0,1,0,0
U7nueKweTWeqhhVDrVoRMw,sksyFBCtJdEq_lUlHTxxng,ZOmf-3NN4Z59b2Fw6VAM7g,5,2015-02-23 16:19:07,"amazing breakfast, amazing red potatoes and sk...",Las Vegas,NV,89147,36.113917,-115.308625,4.5,797,0,"Burgers, American (Traditional), Restaurants, ...",2,4,2011-10-29 04:49:17,,"eyk9XgNeeWPOs_f_qg-Ubg, eH1OL2gu9dW0hvzBD-DA_Q...",1,4.00,"2014-10-28 17:30:11, 2014-10-29 20:57:57, 2014...",0,12,1,323,0,0
s6KNw-8_kefMMtWWY1n_gw,RFKtICzEKGkgyu6DST9QjA,Q-fXNh68OldNdotEVEJuhQ,5,2018-09-13 22:03:13,Neighborhood bar were the locals hangout. Mad...,Henderson,NV,89052,36.006452,-115.111569,4.0,432,1,"American (New), Nightlife, Bars, American (Tra...",2,119,2013-08-12 14:51:22,"2017,2018","gGuAM6Cw1VXJGLssm24ehA, BhawhWz3fD_apxlZv1sMeQ...",5,4.39,"2015-08-25 19:44:31, 2015-08-25 23:59:28, 2015...",0,129,22,69,2,2018
P2El64nL_7PXJqEidv_C9A,MFGDwMQJijNc0mHv1s_BUQ,dc6sPg9kNliz_Cy2yX19tw,2,2014-02-18 04:13:04,Some friends and I were meeting up for sushi a...,Phoenix,AZ,85032,33.600378,-111.978651,3.0,267,1,"Japanese, Sushi Bars, Restaurants",2,180,2010-01-14 17:25:11,"2010,2011,2012,2013,2014","9YRFLVFVbHGAJ1weFx5zqw, PeLGa5vUR8_mcsn-fn42Jg...",22,3.94,"2010-04-08 02:23:53, 2010-05-31 20:18:16, 2010...",4,878,111,345,5,2014
VyMj6vHkn_1OSYiwz88T3w,DEMQj549-Ez-CkSE4tHsKw,5N8R7ALESZ30EoAzVJtabw,4,2017-05-25 00:17:13,This small restaurant is located in Kensington...,Toronto,ON,M5T 2K2,43.654647,-79.400561,3.5,309,1,"Breakfast & Brunch, American (Traditional), Ch...",2,46,2011-05-19 14:26:15,,"4jErA6Yp8jDvJ355M45TZA, -XfmaPe3bc4LhvdjVbZvBQ...",1,4.00,"2015-03-04 17:09:37, 2015-03-04 23:59:28, 2015...",0,36,4,10,0,0
gtljdgwVcrucDtaJe1VIMA,4UgCYM-rbqzukAJyAU_95Q,wH4Q0y8C-lkq21yf4WWedw,4,2017-01-06 14:18:57,"Very clean and hip location, as most Nekter's ...",Scottsdale,AZ,85260,33.580474,-111.881062,4.0,98,1,"Acai Bowls, Restaurants, Gluten-Free, Ice Crea...",2,125,2012-04-30 01:23:49,2016,"kIP1SVkdxxY6Qq1zKt34mA, rpDeMW5uB6VtbwW67PJhlw...",9,4.37,"2015-01-18 16:13:04, 2015-01-20 21:21:56, 2015...",4,351,32,556,1,2016

In [15]:
test.head(5)

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,restaurant_checkins,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count,user_elite_most_recent
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035,1148,1596,3,2016
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2,1,0,0,0
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37,0,729,0,0
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974,275,264,10,2018
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6,0,1,0,0

In [16]:
def count_checkins(x):
    checkin_count = 0 
    if x in ['None', None, '']:
        checkin_count = 0
    else:
        y = x.split(',')
        checkin_count = len(y)
    return checkin_count

test['restaurant_checkin_count'] = test.restaurant_checkins.apply(count_checkins)
test.head(10)

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_categories,restaurant_price_range,user_review_count,user_yelping_since,user_elite,user_friends,user_fans,user_average_stars_given,restaurant_checkins,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count,user_elite_most_recent,restaurant_checkin_count
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,"American (Traditional), Venues & Event Spaces,...",2,421,2010-03-31 04:45:14,"2014,2015,2016","jVYzrVblDFSuL3GHtt8ZSA, 9TTW2jOnT31vEY7i1BcQNg...",136,3.90,"2010-02-12 01:53:51, 2010-03-02 16:40:24, 2010...",5,5035,1148,1596,3,2016,8577
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,"Fish & Chips, Southern, Restaurants, Seafood",2,6,2015-05-12 19:44:07,,None,0,4.83,"2012-05-23 23:37:53, 2012-06-02 23:37:58, 2013...",1,2,1,0,0,0,23
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,"Restaurants, Italian, Pizza, Sandwiches",1,21,2010-06-14 04:52:50,,"8ZbByfd9z8G-57-yDO4CCQ, 5b1dFmlSff_uxqI4W15C1w...",1,3.30,"2010-07-17 01:05:48, 2010-07-24 02:09:31, 2010...",0,37,0,729,0,0,1227
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,"Coffee & Tea, Restaurants, Cafes, Food",1,684,2008-05-14 19:13:56,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2018","FokgHC5GuMddOY-E5Qco9g, 2g42CyH5j-VuDypkVhYcmQ...",43,3.86,"2012-07-10 23:09:44, 2012-07-14 14:46:21, 2012...",2,2974,275,264,10,2018,358
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,"Restaurants, Mexican",1,10,2012-08-29 06:35:52,,Z40Pf1rkPStbSJ9OXRVA2g,0,4.76,"2015-07-15 03:56:39, 2015-07-17 04:05:41, 2015...",0,6,0,1,0,0,57
U7nueKweTWeqhhVDrVoRMw,sksyFBCtJdEq_lUlHTxxng,ZOmf-3NN4Z59b2Fw6VAM7g,5,2015-02-23 16:19:07,"amazing breakfast, amazing red potatoes and sk...",Las Vegas,NV,89147,36.113917,-115.308625,4.5,797,0,"Burgers, American (Traditional), Restaurants, ...",2,4,2011-10-29 04:49:17,,"eyk9XgNeeWPOs_f_qg-Ubg, eH1OL2gu9dW0hvzBD-DA_Q...",1,4.00,"2014-10-28 17:30:11, 2014-10-29 20:57:57, 2014...",0,12,1,323,0,0,1667
s6KNw-8_kefMMtWWY1n_gw,RFKtICzEKGkgyu6DST9QjA,Q-fXNh68OldNdotEVEJuhQ,5,2018-09-13 22:03:13,Neighborhood bar were the locals hangout. Mad...,Henderson,NV,89052,36.006452,-115.111569,4.0,432,1,"American (New), Nightlife, Bars, American (Tra...",2,119,2013-08-12 14:51:22,"2017,2018","gGuAM6Cw1VXJGLssm24ehA, BhawhWz3fD_apxlZv1sMeQ...",5,4.39,"2015-08-25 19:44:31, 2015-08-25 23:59:28, 2015...",0,129,22,69,2,2018,979
P2El64nL_7PXJqEidv_C9A,MFGDwMQJijNc0mHv1s_BUQ,dc6sPg9kNliz_Cy2yX19tw,2,2014-02-18 04:13:04,Some friends and I were meeting up for sushi a...,Phoenix,AZ,85032,33.600378,-111.978651,3.0,267,1,"Japanese, Sushi Bars, Restaurants",2,180,2010-01-14 17:25:11,"2010,2011,2012,2013,2014","9YRFLVFVbHGAJ1weFx5zqw, PeLGa5vUR8_mcsn-fn42Jg...",22,3.94,"2010-04-08 02:23:53, 2010-05-31 20:18:16, 2010...",4,878,111,345,5,2014,573
VyMj6vHkn_1OSYiwz88T3w,DEMQj549-Ez-CkSE4tHsKw,5N8R7ALESZ30EoAzVJtabw,4,2017-05-25 00:17:13,This small restaurant is located in Kensington...,Toronto,ON,M5T 2K2,43.654647,-79.400561,3.5,309,1,"Breakfast & Brunch, American (Traditional), Ch...",2,46,2011-05-19 14:26:15,,"4jErA6Yp8jDvJ355M45TZA, -XfmaPe3bc4LhvdjVbZvBQ...",1,4.00,"2015-03-04 17:09:37, 2015-03-04 23:59:28, 2015...",0,36,4,10,0,0,433
gtljdgwVcrucDtaJe1VIMA,4UgCYM-rbqzukAJyAU_95Q,wH4Q0y8C-lkq21yf4WWedw,4,2017-01-06 14:18:57,"Very clean and hip location, as most Nekter's ...",Scottsdale,AZ,85260,33.580474,-111.881062,4.0,98,1,"Acai Bowls, Restaurants, Gluten-Free, Ice Crea...",2,125,2012-04-30 01:23:49,2016,"kIP1SVkdxxY6Qq1zKt34mA, rpDeMW5uB6VtbwW67PJhlw...",9,4.37,"2015-01-18 16:13:04, 2015-01-20 21:21:56, 2015...",4,351,32,556,1,2016,388

In [17]:
test.drop(labels=['restaurant_categories', 'user_friends', 'user_elite', 'restaurant_checkins'], axis=1, inplace=True)
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   10000 non-null  object
 1   business_id               10000 non-null  object
 2   review_stars              10000 non-null  int64
 3   review_date               10000 non-null  datetime64[ns]
 4   review_text               10000 non-null  object
 5   restaurant_city           10000 non-null  object
 6   restaurant_state          10000 non-null  object
 7   restaurant_postal_code    10000 non-null  object
 8   restaurant_latitude       10000 non-null  float64
 9   restaurant_longitude      10000 non-null  float64
 10  restaurant_overall_stars  10000 non-null  float64
 11  restaurant_review_count   10000 non-null  int64
 12  restaurant_is_open        10000 non-null  int64
 13  restaurant_price_range    9791 non-null   object
 14  user_review_count         10000 non-null  int64
 15  user_yelping_since        10000 non-null  object
 16  user_fans                 10000 non-null  int64
 17  user_average_stars_given  10000 non-null  float64
 18  review_total_positives    10000 non-null  int64
 19  user_total_positives      10000 non-null  int64
 20  user_total_compliments    10000 non-null  int64
 21  user_friends_count        10000 non-null  int64
 22  user_elite_count          10000 non-null  int64
 23  user_elite_most_recent    10000 non-null  object
 24  restaurant_checkin_count  10000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(11), object(9)
memory usage: 2.0+ MB

### Deal With Nan/Null Values

In [18]:
# Restaurant Price Range only column with Nan/Null values.
# Only a small percentage were Nan/Null so dropping all rows with the Nan/Nulls
# Considered filling the Nan/Nulls but determined it wasn't worth the effort.
# Other Nan/Nulls avoided during sql inner joins and counts of columns done above.
test.dropna(inplace=True)

### Convert Data Types to Correct Types for Column

In [19]:
test['user_yelp_start'] = pd.to_datetime(test['user_yelping_since'])
print(test.info())
test.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   9791 non-null   object
 1   business_id               9791 non-null   object
 2   review_stars              9791 non-null   int64
 3   review_date               9791 non-null   datetime64[ns]
 4   review_text               9791 non-null   object
 5   restaurant_city           9791 non-null   object
 6   restaurant_state          9791 non-null   object
 7   restaurant_postal_code    9791 non-null   object
 8   restaurant_latitude       9791 non-null   float64
 9   restaurant_longitude      9791 non-null   float64
 10  restaurant_overall_stars  9791 non-null   float64
 11  restaurant_review_count   9791 non-null   int64
 12  restaurant_is_open        9791 non-null   int64
 13  restaurant_price_range    9791 non-null   object
 14  user_review_count         9791 non-null   int64
 15  user_yelping_since        9791 non-null   object
 16  user_fans                 9791 non-null   int64
 17  user_average_stars_given  9791 non-null   float64
 18  review_total_positives    9791 non-null   int64
 19  user_total_positives      9791 non-null   int64
 20  user_total_compliments    9791 non-null   int64
 21  user_friends_count        9791 non-null   int64
 22  user_elite_count          9791 non-null   int64
 23  user_elite_most_recent    9791 non-null   object
 24  restaurant_checkin_count  9791 non-null   int64
 25  user_yelp_start           9791 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(4), int64(11), object(9)
memory usage: 2.0+ MB
None

,user_id,business_id,review_stars,review_date,review_text,restaurant_city,restaurant_state,restaurant_postal_code,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,restaurant_price_range,user_review_count,user_yelping_since,user_fans,user_average_stars_given,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count,user_elite_most_recent,restaurant_checkin_count,user_yelp_start
review_id,,,,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,uxgU5qcy3Gid6mLTXmv3Zg,wUKzaS1MHg94RGM6z8u9mw,4,2014-10-03 06:00:16,So... I fully intended to take photos of my fo...,Scottsdale,AZ,85251,33.500133,-111.928462,4.0,2060,1,2,421,2010-03-31 04:45:14,136,3.90,5,5035,1148,1596,3,2016,8577,2010-03-31 04:45:14
2IyE9gj2aIeB8qKvUNiZPA,-6QThAc8T-Rbh94SRBb8iA,vm17ueG3HPdlC0CQy82Wxw,5,2019-04-13 23:33:13,This place is awesome! Best seafood around! Gr...,Dallas,NC,28034,35.329852,-81.134431,4.0,23,1,2,6,2015-05-12 19:44:07,0,4.83,1,2,1,0,0,0,23,2015-05-12 19:44:07
RdHK7W6vfYB8Y1vnLjNrqQ,5dvkr39ywFUodEqN8FBJ2A,DZfFFSVFVJVxs3vfFVVf0w,2,2019-07-12 04:22:23,Don't let the rating fool you. We ordered del...,Phoenix,AZ,85022,33.641656,-112.068766,4.0,251,1,1,21,2010-06-14 04:52:50,1,3.30,0,37,0,729,0,0,1227,2010-06-14 04:52:50
5sOQf_qH0uvmUbE1eGSIww,g6kWg8sohsmwrQRDaaJakg,0-CXwwVL-u0tc0FOuSExWQ,2,2015-11-23 16:02:09,So I can only really review the breakfast food...,Phoenix,AZ,85034,33.437660,-111.996632,4.0,123,0,1,684,2008-05-14 19:13:56,43,3.86,2,2974,275,264,10,2018,358,2008-05-14 19:13:56
pZsA5BuVDKzVQDz0Onr36g,SWKCWlTs3Dk4Q5AbbUTHoA,QhJT2fro3Dp1AaIVY7pgzQ,5,2016-06-24 04:22:39,awesome. family run place. great taste and ver...,North Las Vegas,NV,89031,36.262378,-115.171470,4.0,43,1,1,10,2012-08-29 06:35:52,0,4.76,0,6,0,1,0,0,57,2012-08-29 06:35:52

In [20]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   9791 non-null   object
 1   business_id               9791 non-null   object
 2   review_stars              9791 non-null   int64
 3   review_date               9791 non-null   datetime64[ns]
 4   review_text               9791 non-null   object
 5   restaurant_city           9791 non-null   object
 6   restaurant_state          9791 non-null   object
 7   restaurant_postal_code    9791 non-null   object
 8   restaurant_latitude       9791 non-null   float64
 9   restaurant_longitude      9791 non-null   float64
 10  restaurant_overall_stars  9791 non-null   float64
 11  restaurant_review_count   9791 non-null   int64
 12  restaurant_is_open        9791 non-null   int64
 13  restaurant_price_range    9791 non-null   object
 14  user_review_count         9791 non-null   int64
 15  user_yelping_since        9791 non-null   object
 16  user_fans                 9791 non-null   int64
 17  user_average_stars_given  9791 non-null   float64
 18  review_total_positives    9791 non-null   int64
 19  user_total_positives      9791 non-null   int64
 20  user_total_compliments    9791 non-null   int64
 21  user_friends_count        9791 non-null   int64
 22  user_elite_count          9791 non-null   int64
 23  user_elite_most_recent    9791 non-null   object
 24  restaurant_checkin_count  9791 non-null   int64
 25  user_yelp_start           9791 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(4), int64(11), object(9)
memory usage: 2.0+ MB

In [21]:
test['restaurant_price'] = pd.to_numeric(test['restaurant_price_range'])
test['user_most_recent_elite'] = pd.to_numeric(test['user_elite_most_recent'])
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   9791 non-null   object
 1   business_id               9791 non-null   object
 2   review_stars              9791 non-null   int64
 3   review_date               9791 non-null   datetime64[ns]
 4   review_text               9791 non-null   object
 5   restaurant_city           9791 non-null   object
 6   restaurant_state          9791 non-null   object
 7   restaurant_postal_code    9791 non-null   object
 8   restaurant_latitude       9791 non-null   float64
 9   restaurant_longitude      9791 non-null   float64
 10  restaurant_overall_stars  9791 non-null   float64
 11  restaurant_review_count   9791 non-null   int64
 12  restaurant_is_open        9791 non-null   int64
 13  restaurant_price_range    9791 non-null   object
 14  user_review_count         9791 non-null   int64
 15  user_yelping_since        9791 non-null   object
 16  user_fans                 9791 non-null   int64
 17  user_average_stars_given  9791 non-null   float64
 18  review_total_positives    9791 non-null   int64
 19  user_total_positives      9791 non-null   int64
 20  user_total_compliments    9791 non-null   int64
 21  user_friends_count        9791 non-null   int64
 22  user_elite_count          9791 non-null   int64
 23  user_elite_most_recent    9791 non-null   object
 24  restaurant_checkin_count  9791 non-null   int64
 25  user_yelp_start           9791 non-null   datetime64[ns]
 26  restaurant_price          9791 non-null   int64
 27  user_most_recent_elite    9791 non-null   int64
dtypes: datetime64[ns](2), float64(4), int64(13), object(9)
memory usage: 2.2+ MB

In [22]:
test.drop(labels=['user_yelping_since', 'restaurant_price_range', 'user_elite_most_recent'], axis=1, inplace=True)
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   9791 non-null   object
 1   business_id               9791 non-null   object
 2   review_stars              9791 non-null   int64
 3   review_date               9791 non-null   datetime64[ns]
 4   review_text               9791 non-null   object
 5   restaurant_city           9791 non-null   object
 6   restaurant_state          9791 non-null   object
 7   restaurant_postal_code    9791 non-null   object
 8   restaurant_latitude       9791 non-null   float64
 9   restaurant_longitude      9791 non-null   float64
 10  restaurant_overall_stars  9791 non-null   float64
 11  restaurant_review_count   9791 non-null   int64
 12  restaurant_is_open        9791 non-null   int64
 13  user_review_count         9791 non-null   int64
 14  user_fans                 9791 non-null   int64
 15  user_average_stars_given  9791 non-null   float64
 16  review_total_positives    9791 non-null   int64
 17  user_total_positives      9791 non-null   int64
 18  user_total_compliments    9791 non-null   int64
 19  user_friends_count        9791 non-null   int64
 20  user_elite_count          9791 non-null   int64
 21  restaurant_checkin_count  9791 non-null   int64
 22  user_yelp_start           9791 non-null   datetime64[ns]
 23  restaurant_price          9791 non-null   int64
 24  user_most_recent_elite    9791 non-null   int64
dtypes: datetime64[ns](2), float64(4), int64(13), object(6)
memory usage: 1.9+ MB

In [23]:
'''
Index is used as unique identifier. May be able to replace it with a int64.
user_id and business_id may be able to be deleted. Not used in models.
Location features can probably be reduced or reorganized.
Can split off review_text for now if not being used.
'''
test.memory_usage(deep=True)

Index                        773489
user_id                      773489
business_id                  773489
review_stars                  78328
review_date                   78328
review_text                 6169569
restaurant_city              647397
restaurant_state             577669
restaurant_postal_code       610527
restaurant_latitude           78328
restaurant_longitude          78328
restaurant_overall_stars      78328
restaurant_review_count       78328
restaurant_is_open            78328
user_review_count             78328
user_fans                     78328
user_average_stars_given      78328
review_total_positives        78328
user_total_positives          78328
user_total_compliments        78328
user_friends_count            78328
user_elite_count              78328
restaurant_checkin_count      78328
user_yelp_start               78328
restaurant_price              78328
user_most_recent_elite        78328
dtype: int64

In [24]:
test.drop(labels=['restaurant_city', 'restaurant_state', 'restaurant_postal_code', 'user_id', 'business_id'], axis=1, inplace=True)
test.memory_usage(deep=True)

Index                        773489
review_stars                  78328
review_date                   78328
review_text                 6169569
restaurant_latitude           78328
restaurant_longitude          78328
restaurant_overall_stars      78328
restaurant_review_count       78328
restaurant_is_open            78328
user_review_count             78328
user_fans                     78328
user_average_stars_given      78328
review_total_positives        78328
user_total_positives          78328
user_total_compliments        78328
user_friends_count            78328
user_elite_count              78328
restaurant_checkin_count      78328
user_yelp_start               78328
restaurant_price              78328
user_most_recent_elite        78328
dtype: int64

### Split off review text

In [25]:
review_text_df = test['review_text']
review_text_df.head()

review_id
X2-uWEe8FhUe8WhR-nGaDQ    So... I fully intended to take photos of my fo...
2IyE9gj2aIeB8qKvUNiZPA    This place is awesome! Best seafood around! Gr...
RdHK7W6vfYB8Y1vnLjNrqQ    Don't let the rating fool you.  We ordered del...
5sOQf_qH0uvmUbE1eGSIww    So I can only really review the breakfast food...
pZsA5BuVDKzVQDz0Onr36g    awesome. family run place. great taste and ver...
Name: review_text, dtype: object

In [26]:
test.drop(labels=['review_text'], axis=1, inplace=True)
test.memory_usage(deep=True)

Index                       773489
review_stars                 78328
review_date                  78328
restaurant_latitude          78328
restaurant_longitude         78328
restaurant_overall_stars     78328
restaurant_review_count      78328
restaurant_is_open           78328
user_review_count            78328
user_fans                    78328
user_average_stars_given     78328
review_total_positives       78328
user_total_positives         78328
user_total_compliments       78328
user_friends_count           78328
user_elite_count             78328
restaurant_checkin_count     78328
user_yelp_start              78328
restaurant_price             78328
user_most_recent_elite       78328
dtype: int64

In [27]:
test.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_stars              9791 non-null   int64
 1   review_date               9791 non-null   datetime64[ns]
 2   restaurant_latitude       9791 non-null   float64
 3   restaurant_longitude      9791 non-null   float64
 4   restaurant_overall_stars  9791 non-null   float64
 5   restaurant_review_count   9791 non-null   int64
 6   restaurant_is_open        9791 non-null   int64
 7   user_review_count         9791 non-null   int64
 8   user_fans                 9791 non-null   int64
 9   user_average_stars_given  9791 non-null   float64
 10  review_total_positives    9791 non-null   int64
 11  user_total_positives      9791 non-null   int64
 12  user_total_compliments    9791 non-null   int64
 13  user_friends_count        9791 non-null   int64
 14  user_elite_count          9791 non-null   int64
 15  restaurant_checkin_count  9791 non-null   int64
 16  user_yelp_start           9791 non-null   datetime64[ns]
 17  restaurant_price          9791 non-null   int64
 18  user_most_recent_elite    9791 non-null   int64
dtypes: datetime64[ns](2), float64(4), int64(13)
memory usage: 2.2 MB

### Feature Engineering

In [28]:
# Difference between star counts
# review_stars - user_average_stars_given
test['review_stars_v_user_average'] = test['review_stars'] - test['user_average_stars_given']
# review_stars - restaurant_overall_stars
test['review_stars_v_restaurant_average'] = test['review_stars'] - test['restaurant_overall_stars']

In [29]:
test['user_years_since_last_elite'] = 2020 - test['user_most_recent_elite']
test.head(10)

,review_stars,review_date,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,user_review_count,user_fans,user_average_stars_given,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count,restaurant_checkin_count,user_yelp_start,restaurant_price,user_most_recent_elite,review_stars_v_user_average,review_stars_v_restaurant_average,user_years_since_last_elite
review_id,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,4,2014-10-03 06:00:16,33.500133,-111.928462,4.0,2060,1,421,136,3.90,5,5035,1148,1596,3,8577,2010-03-31 04:45:14,2,2016,0.10,0.0,4
2IyE9gj2aIeB8qKvUNiZPA,5,2019-04-13 23:33:13,35.329852,-81.134431,4.0,23,1,6,0,4.83,1,2,1,0,0,23,2015-05-12 19:44:07,2,0,0.17,1.0,2020
RdHK7W6vfYB8Y1vnLjNrqQ,2,2019-07-12 04:22:23,33.641656,-112.068766,4.0,251,1,21,1,3.30,0,37,0,729,0,1227,2010-06-14 04:52:50,1,0,-1.30,-2.0,2020
5sOQf_qH0uvmUbE1eGSIww,2,2015-11-23 16:02:09,33.437660,-111.996632,4.0,123,0,684,43,3.86,2,2974,275,264,10,358,2008-05-14 19:13:56,1,2018,-1.86,-2.0,2
pZsA5BuVDKzVQDz0Onr36g,5,2016-06-24 04:22:39,36.262378,-115.171470,4.0,43,1,10,0,4.76,0,6,0,1,0,57,2012-08-29 06:35:52,1,0,0.24,1.0,2020
U7nueKweTWeqhhVDrVoRMw,5,2015-02-23 16:19:07,36.113917,-115.308625,4.5,797,0,4,1,4.00,0,12,1,323,0,1667,2011-10-29 04:49:17,2,0,1.00,0.5,2020
s6KNw-8_kefMMtWWY1n_gw,5,2018-09-13 22:03:13,36.006452,-115.111569,4.0,432,1,119,5,4.39,0,129,22,69,2,979,2013-08-12 14:51:22,2,2018,0.61,1.0,2
P2El64nL_7PXJqEidv_C9A,2,2014-02-18 04:13:04,33.600378,-111.978651,3.0,267,1,180,22,3.94,4,878,111,345,5,573,2010-01-14 17:25:11,2,2014,-1.94,-1.0,6
VyMj6vHkn_1OSYiwz88T3w,4,2017-05-25 00:17:13,43.654647,-79.400561,3.5,309,1,46,1,4.00,0,36,4,10,0,433,2011-05-19 14:26:15,2,0,0.00,0.5,2020
gtljdgwVcrucDtaJe1VIMA,4,2017-01-06 14:18:57,33.580474,-111.881062,4.0,98,1,125,9,4.37,4,351,32,556,1,388,2012-04-30 01:23:49,2,2016,-0.37,0.0,4

In [30]:
test.drop(labels=['user_most_recent_elite'], inplace=True, axis=1)

In [31]:
test['user_days_active_at_review_time'] = (test['review_date'] - test['user_yelp_start']).dt.days

In [32]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   review_stars                       9791 non-null   int64
 1   review_date                        9791 non-null   datetime64[ns]
 2   restaurant_latitude                9791 non-null   float64
 3   restaurant_longitude               9791 non-null   float64
 4   restaurant_overall_stars           9791 non-null   float64
 5   restaurant_review_count            9791 non-null   int64
 6   restaurant_is_open                 9791 non-null   int64
 7   user_review_count                  9791 non-null   int64
 8   user_fans                          9791 non-null   int64
 9   user_average_stars_given           9791 non-null   float64
 10  review_total_positives             9791 non-null   int64
 11  user_total_positives               9791 non-null   int64
 12  user_total_compliments             9791 non-null   int64
 13  user_friends_count                 9791 non-null   int64
 14  user_elite_count                   9791 non-null   int64
 15  restaurant_checkin_count           9791 non-null   int64
 16  user_yelp_start                    9791 non-null   datetime64[ns]
 17  restaurant_price                   9791 non-null   int64
 18  review_stars_v_user_average        9791 non-null   float64
 19  review_stars_v_restaurant_average  9791 non-null   float64
 20  user_years_since_last_elite        9791 non-null   int64
 21  user_days_active_at_review_time    9791 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(14)
memory usage: 1.7+ MB

### Target Creation

In [33]:
database_init_datetime = pd.to_datetime('2020-3-25 19:13:01')
test['days_since_review'] = (database_init_datetime - test.review_date).dt.days

In [34]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   review_stars                       9791 non-null   int64
 1   review_date                        9791 non-null   datetime64[ns]
 2   restaurant_latitude                9791 non-null   float64
 3   restaurant_longitude               9791 non-null   float64
 4   restaurant_overall_stars           9791 non-null   float64
 5   restaurant_review_count            9791 non-null   int64
 6   restaurant_is_open                 9791 non-null   int64
 7   user_review_count                  9791 non-null   int64
 8   user_fans                          9791 non-null   int64
 9   user_average_stars_given           9791 non-null   float64
 10  review_total_positives             9791 non-null   int64
 11  user_total_positives               9791 non-null   int64
 12  user_total_compliments             9791 non-null   int64
 13  user_friends_count                 9791 non-null   int64
 14  user_elite_count                   9791 non-null   int64
 15  restaurant_checkin_count           9791 non-null   int64
 16  user_yelp_start                    9791 non-null   datetime64[ns]
 17  restaurant_price                   9791 non-null   int64
 18  review_stars_v_user_average        9791 non-null   float64
 19  review_stars_v_restaurant_average  9791 non-null   float64
 20  user_years_since_last_elite        9791 non-null   int64
 21  user_days_active_at_review_time    9791 non-null   int64
 22  days_since_review                  9791 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(15)
memory usage: 1.8+ MB

In [35]:
test.head(5)

,review_stars,review_date,restaurant_latitude,restaurant_longitude,restaurant_overall_stars,restaurant_review_count,restaurant_is_open,user_review_count,user_fans,user_average_stars_given,review_total_positives,user_total_positives,user_total_compliments,user_friends_count,user_elite_count,restaurant_checkin_count,user_yelp_start,restaurant_price,review_stars_v_user_average,review_stars_v_restaurant_average,user_years_since_last_elite,user_days_active_at_review_time,days_since_review
review_id,,,,,,,,,,,,,,,,,,,,,,,
X2-uWEe8FhUe8WhR-nGaDQ,4,2014-10-03 06:00:16,33.500133,-111.928462,4.0,2060,1,421,136,3.90,5,5035,1148,1596,3,8577,2010-03-31 04:45:14,2,0.10,0.0,4,1647,2000
2IyE9gj2aIeB8qKvUNiZPA,5,2019-04-13 23:33:13,35.329852,-81.134431,4.0,23,1,6,0,4.83,1,2,1,0,0,23,2015-05-12 19:44:07,2,0.17,1.0,2020,1432,346
RdHK7W6vfYB8Y1vnLjNrqQ,2,2019-07-12 04:22:23,33.641656,-112.068766,4.0,251,1,21,1,3.30,0,37,0,729,0,1227,2010-06-14 04:52:50,1,-1.30,-2.0,2020,3314,257
5sOQf_qH0uvmUbE1eGSIww,2,2015-11-23 16:02:09,33.437660,-111.996632,4.0,123,0,684,43,3.86,2,2974,275,264,10,358,2008-05-14 19:13:56,1,-1.86,-2.0,2,2748,1584
pZsA5BuVDKzVQDz0Onr36g,5,2016-06-24 04:22:39,36.262378,-115.171470,4.0,43,1,10,0,4.76,0,6,0,1,0,57,2012-08-29 06:35:52,1,0.24,1.0,2020,1394,1370

In [36]:
test['TARGET_time_adjusted_review_positives'] = test['review_total_positives'] / test['days_since_review']

In [37]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   review_stars                           9791 non-null   int64
 1   review_date                            9791 non-null   datetime64[ns]
 2   restaurant_latitude                    9791 non-null   float64
 3   restaurant_longitude                   9791 non-null   float64
 4   restaurant_overall_stars               9791 non-null   float64
 5   restaurant_review_count                9791 non-null   int64
 6   restaurant_is_open                     9791 non-null   int64
 7   user_review_count                      9791 non-null   int64
 8   user_fans                              9791 non-null   int64
 9   user_average_stars_given               9791 non-null   float64
 10  review_total_positives                 9791 non-null   int64
 11  user_total_positives                   9791 non-null   int64
 12  user_total_compliments                 9791 non-null   int64
 13  user_friends_count                     9791 non-null   int64
 14  user_elite_count                       9791 non-null   int64
 15  restaurant_checkin_count               9791 non-null   int64
 16  user_yelp_start                        9791 non-null   datetime64[ns]
 17  restaurant_price                       9791 non-null   int64
 18  review_stars_v_user_average            9791 non-null   float64
 19  review_stars_v_restaurant_average      9791 non-null   float64
 20  user_years_since_last_elite            9791 non-null   int64
 21  user_days_active_at_review_time        9791 non-null   int64
 22  days_since_review                      9791 non-null   int64
 23  TARGET_time_adjusted_review_positives  9791 non-null   float64
dtypes: datetime64[ns](2), float64(7), int64(15)
memory usage: 1.9+ MB

In [38]:
time_related_features_to_drop = ['days_since_review', 'user_yelp_start', 'review_date', 'review_total_positives']
test.drop(labels=time_related_features_to_drop, inplace=True, axis=1)

In [39]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   review_stars                           9791 non-null   int64
 1   restaurant_latitude                    9791 non-null   float64
 2   restaurant_longitude                   9791 non-null   float64
 3   restaurant_overall_stars               9791 non-null   float64
 4   restaurant_review_count                9791 non-null   int64
 5   restaurant_is_open                     9791 non-null   int64
 6   user_review_count                      9791 non-null   int64
 7   user_fans                              9791 non-null   int64
 8   user_average_stars_given               9791 non-null   float64
 9   user_total_positives                   9791 non-null   int64
 10  user_total_compliments                 9791 non-null   int64
 11  user_friends_count                     9791 non-null   int64
 12  user_elite_count                       9791 non-null   int64
 13  restaurant_checkin_count               9791 non-null   int64
 14  restaurant_price                       9791 non-null   int64
 15  review_stars_v_user_average            9791 non-null   float64
 16  review_stars_v_restaurant_average      9791 non-null   float64
 17  user_years_since_last_elite            9791 non-null   int64
 18  user_days_active_at_review_time        9791 non-null   int64
 19  TARGET_time_adjusted_review_positives  9791 non-null   float64
dtypes: float64(7), int64(13)
memory usage: 1.6+ MB

### Organize features.

In [40]:
test.columns

Index(['review_stars', 'restaurant_latitude', 'restaurant_longitude', 'restaurant_overall_stars', 'restaurant_review_count', 'restaurant_is_open', 'user_review_count', 'user_fans', 'user_average_stars_given', 'user_total_positives', 'user_total_compliments', 'user_friends_count', 'user_elite_count', 'restaurant_checkin_count', 'restaurant_price', 'review_stars_v_user_average', 'review_stars_v_restaurant_average', 'user_years_since_last_elite', 'user_days_active_at_review_time',
       'TARGET_time_adjusted_review_positives'],
      dtype='object')

In [41]:
features_ordered = ['TARGET_time_adjusted_review_positives', 'review_stars', 'review_stars_v_user_average', 'review_stars_v_restaurant_average', 'restaurant_latitude', 'restaurant_longitude', 'restaurant_overall_stars', 'restaurant_review_count', 'restaurant_checkin_count', 'restaurant_is_open', 'restaurant_price', 'user_average_stars_given', 'user_review_count', 'user_total_positives', 'user_total_compliments', 'user_friends_count', 'user_fans', 'user_elite_count', 'user_years_since_last_elite',
       'user_days_active_at_review_time']
test = test[features_ordered]

In [42]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9791 entries, X2-uWEe8FhUe8WhR-nGaDQ to S970_2R0ow-9GKm7OIWitg
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   TARGET_time_adjusted_review_positives  9791 non-null   float64
 1   review_stars                           9791 non-null   int64
 2   review_stars_v_user_average            9791 non-null   float64
 3   review_stars_v_restaurant_average      9791 non-null   float64
 4   restaurant_latitude                    9791 non-null   float64
 5   restaurant_longitude                   9791 non-null   float64
 6   restaurant_overall_stars               9791 non-null   float64
 7   restaurant_review_count                9791 non-null   int64
 8   restaurant_checkin_count               9791 non-null   int64
 9   restaurant_is_open                     9791 non-null   int64
 10  restaurant_price                       9791 non-null   int64
 11  user_average_stars_given               9791 non-null   float64
 12  user_review_count                      9791 non-null   int64
 13  user_total_positives                   9791 non-null   int64
 14  user_total_compliments                 9791 non-null   int64
 15  user_friends_count                     9791 non-null   int64
 16  user_fans                              9791 non-null   int64
 17  user_elite_count                       9791 non-null   int64
 18  user_years_since_last_elite            9791 non-null   int64
 19  user_days_active_at_review_time        9791 non-null   int64
dtypes: float64(7), int64(13)
memory usage: 1.6+ MB

### Save Completed Data to New Postgres Table